replicateproject/replicateproject/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.testlist.as_view(),name='home'),
    path('<pk>/', views.testdetail.as_view(),name='detail'),
    path('create/<pk>', views.testcreate.as_view()),
    path('delete/<pk>', views.testdelete.as_view()),



]

replicateproject/testapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class test(models.Model):
    name=models.CharField(max_length=64)
    cross=models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse ('detail',kwargs={'pk':self.pk})

replicateproject/testapp/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,DeleteView,TemplateView
from testapp.models import test
from django.urls import reverse_lazy# Create your views here.



class testlist(ListView):
    model=test




class testdetail(DetailView):
    model=test

class testcreate(CreateView):
    model=test
    fields=('name','cross')
class testdelete(DeleteView):
    model=test
    success_url=reverse_lazy('home')

replicateproject/replicateproject/templates/testapp/base.html
<!DOCTYPE html>
{% load static files%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/replicate.css"%}">

    <title></title>

  </head>
  <body>
    <div class="container">
      {% block body_block %}
      {% endblock%}

    </div>}

  </body>
</html>

replicateproject/replicateproject/templates/testapp/test_confirm_delete.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}

           <h1>ARE SURE TO DELETE{{test.name}}</h1>
           {% for test in test_list %}
               <form  method="post">
                 {%csrf_token%}
                 <input type="submit" class="btn btn-lg btn-danger " value="delete ">
                 <a href="/{{test.id}}" class= "btn btn-lg btn-sucess"> cancel</a>
               </form>
            {% endfor%}
           {% endblock%}

replicateproject/replicateproject/templates/testapp/test_detail.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}
           <h1>{{test.name}} test information</h1>
           <h2>TEST NAME:{{test.name}}</h2>
           <h2>TEST CROSS:{{ test.cross}}</h2>


           {% endblock%} 

replicateproject/replicateproject/templates/testapp/test_form.html
<!DOCTYPE html>
{% extends "testapp/base.html"%}
  {% block body_block %}
     <h1>TEST DATA  INSERT FORM</h1>
     <form  method="post">
       {{form.as_p}}
       {% csrf_token%}
       <input type="submit" class="btn btn-lg btn-primary" value="INSERT">

     </form>
     {% endblock %} 

replicateproject/replicateproject/templates/testapp/test_list.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}
           <h1> TEST INFORMATION</h1>
              <table  border='2'>
                <thead>
                  <th>NAME</th>
                  <th>DETAIL</th>
                  <th>ADD TO</th>
                  <th>DELETE</th>
                </thead>
              {% for test in test_list %}
                <tr>
                  <td>{{test.name|upper}}</td>
                  <td><a href="/{{test.id }}"> detail</a>  </td>
                  <td>  <a href="/create/{{test.id}}">create </a>  </td>
                  <td> <a href="/delete/{{test.id}}"> delete</a> </td>
                </tr>
               {% endfor%}
             </table><br><br><br>


           {% endblock%}

replicateproject/testapp/templates/testapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <title></title>

  </head>
  <body>
    <div class="container">
      {% block body_block %}
      {% endblock%}

    </div>}

  </body>
</html>

replicateproject/testapp/templates/testapp/test_confirm_delete.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}

           <h1>ARE SURE TO DELETE:  {{test.name}}</h1>

               <form  method="post">
                 {%csrf_token%}
                 <input type="submit" class="btn btn-lg btn-danger " value="delete ">
                 <a href="/{{test.id}}" class= "btn btn-lg btn-sucess"> cancel</a>
               </form>

           {% endblock%}

replicateproject/testapp/templates/testapp/test_detail.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}
           <h1>{{test.name}} test information</h1>
           <h2>TEST NAME:{{test.name}}</h2>
           <h2>TEST CROSS:{{ test.cross}}</h2>


           {% endblock%}

replicateproject/testapp/templates/testapp/test_form.html
<!DOCTYPE html>
{% extends "testapp/base.html"%}
  {% block body_block %}
     <h1>TEST DATA  INSERT FORM</h1>
     <form  method="post">
       {{form.as_p}}
       {% csrf_token%}
       <input type="submit" class="btn btn-lg btn-primary" value="INSERT">

     </form>
     {% endblock %}

replicateproject/testapp/templates/testapp/test_list.html
<!DOCTYPE html>
{% extends 'testapp/base.html'%}
        {% block body_block%}
           <h1> TEST INFORMATION</h1>
              <table  border='2'>
                <thead>
                  <th>NAME</th>
                  <th>DETAIL</th>
                  <th>ADD TO</th>
                  <th>DELETE</th>
                </thead>
              {% for test in test_list %}
                <tr>
                  <td>{{test.name|upper}}</td>
                  <td><a href="/{{test.id }}"> detail</a>  </td>
                  <td>  <a href="/create/{{test.id}}">create </a>  </td>
                  <td> <a href="/delete/{{test.id}}"> delete</a> </td>
                </tr>
               {% endfor%}
             </table><br><br><br>


           {% endblock%}